version: '3'

services:
  api:
      container_name: bc.api
      image: bc
      ports:
        - "8080:8080"
      privileged: true
      networks:
        - code-network

  mysql-db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456!
    networks:
      - code-network

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - code-network

networks:
  code-network:
      driver: bridge